---
- name: Install bzip2 if not present already
  ansible.builtin.package:
    name: bzip2
    state: present

- name: Install/update restic
  ansible.builtin.include_tasks:
    file: restic.yml

- name: Install/update backrest
  ansible.builtin.include_tasks:
    file: install.yml
