---
- name: Run act_runner registration command
  ansible.builtin.command:
    cmd: >-
      /usr/local/bin/act_runner register --no-interactive
      --instance {{ gitea_runner_instance }}
      --token {{ gitea_runner_token }}
    chdir: "/home/{{ gitea_runner_user }}/"
  register: command_output
