---
- name: Create gitea act_runner service
  ansible.builtin.copy:
    dest: /etc/systemd/system/act_runner.service
    content: |
      [Unit]
      Description=Gitea Actions runner
      Documentation=https://gitea.com/gitea/act_runner
      After=docker.service

      [Service]
      ExecStart=/usr/local/bin/act_runner daemon
      ExecReload=/bin/kill -s HUP $MAINPID
      WorkingDirectory=/home/{{ gitea_runner_user }}
      TimeoutSec=0
      RestartSec=10
      Restart=always
      User={{ gitea_runner_user }}

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Enable act_runner service
