---
- name: Create cachemover service
  ansible.builtin.copy:
    dest: /etc/systemd/system/cachemover.service
    content: |
      [Unit]
      Description=Executor for cachemover

      [Service]
      Type=oneshot
      ExecStart=/opt/cachemover/cachemover.sh
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Enable cachemover timer

- name: Create cachemover timer
  ansible.builtin.copy:
    dest: /etc/systemd/system/cachemover.timer
    content: |
      [Unit]
      Description=Run cachemover every morning

      [Timer]
      OnCalendar=*-*-* 04:00:00
      RandomizedDelaySec=10m

      [Install]
      WantedBy=timers.target
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Enable cachemover timer
