---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable act_runner service
  ansible.builtin.systemd:
    name: act_runner.service
    enabled: true
    state: started
