---
- name: Cleanup i915 download directory
  ansible.builtin.file:
    path: "/tmp/i915-sriov"
    state: absent

- name: Update grub
  ansible.builtin.command: "update-grub"
  changed_when: true

- name: Update initramfs
  ansible.builtin.command: "update-initramfs -u"
  changed_when: true

- name: Reboot
  ansible.builtin.reboot:
    msg: "Reboot triggered by Ansible: i915_sriov task"
  when: i915_sriov_reboot is true
